"""add CLIP image embedding column and pgvector extension

Stage 3a. The eBay corpus becomes a reference index that listings found on
other sources get matched against, since a foreign listing carries no eBay
catalog id (epid) and so nothing exact can bridge the two.

See docs/decisions/0009-clip-embeddings-pgvector.md.

Hand-written, not autogenerated. Alembic's --autogenerate never emits
CREATE EXTENSION and does not recognise the `vector` type, so it cannot
produce this migration and may well propose dropping the column on a later
run. Check any autogenerated revision that mentions `embedding` before
applying it.

Both columns are nullable. For `embedding` that is a real decision rather than
laziness: a NOT NULL column would need a zero-vector default, and an all-zeros
sentinel sits equidistant from every other vector, forming a fake cluster that
turns up in every k-NN result. "Not embedded yet" must be representable.

Revision ID: 0010
Revises: 0009
Create Date: 2026-07-25

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

revision: str = "0010"
down_revision: Union[str, None] = "0009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Deliberately a literal, not an import of api.models.EMBEDDING_DIM. A
# migration describes the schema as it stood at this revision; importing a
# live constant would mean a later checkpoint swap silently rewrote history,
# and replaying migrations on a fresh database would build a different schema
# than the one this revision actually created.
EMBEDDING_DIM = 512


def upgrade() -> None:
    # Idempotent, and safe on a database where someone already enabled it by
    # hand. Requires the pgvector extension to be available in the image; the
    # project's Postgres container ships with it.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.add_column("listing", sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True))
    op.add_column(
        "listing", sa.Column("embedded_at", sa.DateTime(timezone=True), nullable=True)
    )

    # No ANN index (HNSW/IVFFlat) yet, on purpose. An exact scan measured
    # 29 ms in Postgres over 10,484 embedded rows, at 100% recall. Stage 4's
    # queries are also *filtered* k-NN (by source, sale confidence, category),
    # which ANN indexes handle badly: they search the graph first and filter
    # after, so a selective filter can leave almost nothing. Revisit near
    # 100k rows or when a query is measured above ~100 ms, then HNSW with
    # vector_cosine_ops.


def downgrade() -> None:
    op.drop_column("listing", "embedded_at")
    op.drop_column("listing", "embedding")
    # Deliberately does NOT drop the extension. It is database-wide, may be in
    # use by something outside this project, and leaving it costs nothing.
